### ISSUE TITLE
DatasetType in the eml profile?

### ISSUE THREAD

**Issue by ManonGros** [gbif/eml-profile#11]
I can see that the EML 2.2 has a `datasetType` element: https://rs.gbif.org/schema/eml-2.2.0/eml-dataset.xsd

> **summary**: DatasetType is the base type for the dataset element.
> **description**: DatasetType is the base type for the dataset element. The dataset field encompasses all information about a single dataset. A dataset is defined as all of the information describing a data collection event. This event may take place over some period of time and include many actual collections (a time series or remote sensing application) or it could be just one actual collection (a day in the field).

But I don't see it in the GBIF EML (maybe I missed it?)
It seems like it could be a place where the dataset categories could be shared/stored: https://github.com/gbif/registry/issues/247

Would it make sense to have it in the GBIF EML, maybe associated with the category defined in the linked issue? Tagging @CecSve

**Comment by CecSve** [comment]
Might be a way to implement the [datasetCategory vocabulary](https://registry.gbif-uat.org/vocabulary/DatasetCategory)?

**Comment by mdoering** [comment]
the `DatasetType` is just an XML Schema artifact, defining a reusable complex type of xml elements and attributes. It is not a vocabulary and not exposed in instance documents. It's more like a reusable snippet/variable within the xml schema document

**Comment by mike-podolskiy90** [comment]
Adding more context.

`DatasetType` is a type of the element `dataset` and we already have the `dataset` element in the EML. It's a complex type that describes basically all EML content we can have inside the `dataset` block.

In XML Schema Definition (XSD), the `<complexType>` element is used to define complex elements that can contain other elements and attributes, as opposed to simple elements, which contain only text or atomic data (like strings, numbers, or dates).

Hope that helps.

**Comment by ManonGros** [comment]
Thank you all, it is good to know.
