### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AbbyBenson** [gbif/eml-profile#2]
Link to the Resource Guide in the ReadMe for this repo is broken. Same for the How-to guide.

**Comment by MattBlissett** [comment]
@dnoesgaard, I'm not sure how these links are maintained. I could just change the ReadMe in this repository, but there are probably other references to https://www.gbif.org/resource/80640 and https://www.gbif.org/resource/80641.

The Resource Guide is here: https://www.gbif.org/sites/default/files/gbif_resource/resource-80640/gbif_metadata_profile_guide_en_v1.pdf

And the How-to is here: https://ipt.gbif.org/manual/en/ipt/2.5/gbif-metadata-profile

**Comment by dnoesgaard** [comment]
Thanks, @MattBlissett. You can go ahead and correct the links in the readme file. I will figure out if we need to redirect these...
